### ISSUE TITLE
Two images too close together on teaching page

### ISSUE THREAD

**Issue by LeifAndersen** [nuprl/nuprl.github.io#14]
The two images on the teaching page looks a bit jarring.
<img width="1280" alt="screen shot 2015-11-03 at 4 19 49 pm" src="https://cloud.githubusercontent.com/assets/285926/10922009/dcc3f1c2-8246-11e5-821c-388d68e2860a.png">

**Comment by LeifAndersen** [comment]
(It seems like if it was either one image, or not using parallax it would be okay.

Although if I'm the only one who cares about this I'd be fine with closing it.)

**Comment by schuster** [comment]
Closing for now since no one else has commented; we can reopen later if anyone complains.
