### ISSUE TITLE
Add Racket package dependencies

### ISSUE THREAD

**Issue by schuster** [nuprl/nuprl.github.io#22]
List in something like an info.rkt, and find a way to check that the dependencies are sufficient in the automated build, too.

**Comment by maxsnew** [comment]
+1000

**Comment by wilbowma** [comment]
I'm using gregor-lib for handling datetime stuff.

**Comment by bennn** [comment]
The current Makefile installs all the packages on a fresh install of Racket 6.5
https://github.com/nuprl/nuprl.github.io/blob/master/Makefile#L7

**Comment by wilbowma** [comment]
So can this be closed?

**Comment by schuster** [comment]
Yep, closing.
