### ISSUE TITLE
RFC: DBLP-backed publications page

### ISSUE THREAD

**Issue by schuster** [nuprl/nuprl.github.io#39]
I'm working on redoing the publications page to scrape DBLP, but I'd like to get some feedback on the idea. The work in progress is here: https://github.com/schuster/nuprl.github.io/tree/dblp-pubs

The general plan is to use DBLP as the (mostly) exclusive source of publications, filling in some manual entries for missing information as needed. We'll pull in the XML file for each faculty member (hard-coded), and use that to create the list of entries. Duplicates will be removed by comparing for same title and venue.

A likely incomplete list of open questions:
- What should we do publications without a faculty member author?
- What should we do about former lab members who published with us (e.g. DVH, Sam Tobin-Hochstadt, former students, etc.)?
- Should we filter the faculty publications to only be included if it was while they were part of Northeastern?

@howell or others, thoughts?

**Comment by bennn** [comment]
I think you'll want a date range for each person involved with PRL (students, faculty, visitors). Scrape DBLP for each person, filter the publications within range.

(But this sounds like too much work. If I were in charge I'd do the one-time import for old papers and encourage everyone to keep the list up to date. It's in all our best interest.)

**Comment by schuster** [comment]
Using this scrape for a one-time import may be the way to go (I discussed this a bit with @howell this afternoon). I just worry that eventually (years from now) no one's going to be updating it actively.
