### ISSUE TITLE
Webpage stutters

### ISSUE THREAD

**Issue by LeifAndersen** [nuprl/nuprl.github.io#4]
Webpage stutters when scrolling, causing a very low frame rate. This appears to be doing a very large amount of re-rendering.

**Comment by schuster** [comment]
The designers are working on this issue.

**Comment by schuster** [comment]
Partial fix implemented: at low resolutions, the parallax effect is disabled. We may want to think about disabling the effect altogether.

Alternatively, @BenChung found [an alternative implementation](http://keithclark.co.uk/articles/pure-css-parallax-websites/) that should be much more performant. He also has a branch "parallax-ben" that starts a fix for the issue.
