### ISSUE TITLE
How to Math

### ISSUE THREAD

**Issue by maxsnew** [nuprl/nuprl.github.io#48]
I have a few blog post ideas, but they would all require some amount of inference rules and/or diagrams.

How would I do that?

**Comment by schuster** [comment]
Do you mean how would you generate the diagrams, or how would you include them in the post?

**Comment by maxsnew** [comment]
Like are there nice ways to do this besides generating images and plopping them in

**Comment by schuster** [comment]
Not that I know of. Scribble/Frog might have some nice ways to do Racket-y things like code snippets, but I don't know of any particular way to do it other than just plopping them in however Frog recommends.

**Comment by wilbowma** [comment]
A couple approaches:
1. Use MathJax in a Markdown blog post. This will likely require tweaking frog to support MathJax.
2. Do you math in Redex in a Scribble blog post. This will likely be annoying as hell.
3. Write the math separately in LaTeX and generate images, then link to the images in the normal
   HTML way.

**Comment by gasche** [comment]
I generally dislike using client-side computation when a server-side computation would suffice, but in practice I found it hard to beat [mathJax](http://www.mathjax.org/) in terms of convenience to use and quality of the rendered output.

**Comment by schuster** [comment]
Looks like we have some solutions, so I'm closing this issue. Feel free to open it back up if further problems arise.
