### ISSUE TITLE
Update for New and Old People

### ISSUE THREAD

**Issue by maxsnew** [nuprl/nuprl.github.io#50]
We should update for old students who've graduated and new students and researchers that have joined this semester.

Move these olds to the alumni \o/:
- [x] Asumu
- [x] Paul

Add the newbs. Need pictures, titles and blurbs:
- [x] Dan Patterson 
- [ ] Ming-Ho Yee
- [X] Prof. Heather Miller
- [X] Filip Křikava 
- [ ] Filippo Ghibellini
- [X] Prof. Frank TIp

Dan just got here, but others are coming soon

**Comment by bennn** [comment]
@paulstansifer @takikawa are your dissertations online?

@dbp do you have a favorite picture? ditto for @mhyee

**Comment by mhyee** [comment]
No, I don't have a picture.

**Comment by dbp** [comment]
I'll find a photo.

**Comment by dbp** [comment]
Here's a photo. 
![dbp_small](https://cloud.githubusercontent.com/assets/569509/17650226/bc585030-6216-11e6-9caf-e779c978464f.jpg)

**Comment by paulstansifer** [comment]
My dissertation is here: http://hdl.handle.net/2047/D20206853

Paul

On Fri, Aug 12, 2016 at 7:36 PM, Benjamin Greenman <notifications@github.com

**Comment by dbp** [comment]
Oh, and blurb - "I'm interested in language and type system interoperability - in particular, languages with very different type systems interacting easily and safely". Also - anything I can do to help this?

**Comment by schuster** [comment]
@dbp I've just added both you and @mhyee as members to the nuprl GitHub team, so now you should be able to commit new code if you want (although it might be smart to send a PR instead, since all commits are sent directly to the live website).

Point being, you can clone the repo and add your own info in people.rkt if you like (see README.md for build instructions).

**Comment by bennn** [comment]
@schuster  can you add Heather Miller to the team?

@heathermiller can you put a picture + blurb here, or in a pull request to [the people page](https://github.com/nuprl/nuprl.github.io/blob/src/people.rkt)? (website [here](http://prl.ccs.neu.edu/people.html))

**Comment by schuster** [comment]
Heather is added (or has an invite, anyway).

**Comment by bennn** [comment]
@franktip can you give us a picture + blurb for the PRL website? http://prl.ccs.neu.edu/people.html

**Comment by bennn** [comment]
Let's close this, and open 1 (or 2) new issues:
- need a bio + pic for Ming Ho
- need a bio + pic for Fillippo

**Comment by bennn** [comment]
Yes Ben, lets.
