### ISSUE TITLE
Seminars aren't showing up as past (javascript escaping issue?)

### ISSUE THREAD

**Issue by dbp** [nuprl/nuprl.github.io#70]
Jan pointed out that the old seminars don't show up as grayed out anymore. It looks like the mechanism to gray them was some javascript that compared the date, but it looks like that javascript has been escaped, which means it doesn't run.

Could someone who understands the generation tool, and perhaps what might have changed recently about it, help me out? (maybe @benn, our webmaster?)

(also, if it's easy while poking around, the links to institutions don't work either. They have "@link" as the href...)

**Comment by schuster** [comment]
Similarly, email links on the People page are broken.

I'm looking into this now. It happened as a result of switching the pages from scribble/text to scribble/html; I just don't know enough about @-expressions to know the fix right away.
