### ISSUE TITLE
Code Colors make Numbers Difficult to See

### ISSUE THREAD

**Issue by maxsnew** [nuprl/nuprl.github.io#82]
I was looking at an [an old blog post](http://prl.ccs.neu.edu/blog/2017/09/27/final-algebra-semantics-is-observational-equivalence/) and it numbers in the code look nearly invisible because they are white on a very light background, see the part right after "ghci will tell us".

I see this is defined in https://github.com/nuprl/nuprl.github.io/blob/master/css/pygments.css , does anyone that cares about design have an opinion on what color it should be? Just scrolling through css colors, [darkviolet](https://www.htmlcsscolor.com/hex/9400D3) is easy to read, but probably hard for colorblind people to distinguish from red.

**Comment by mhyee** [comment]
I think it's easier if we keep our issues in the source repo (https://github.com/nuprl/website). This is for build artifacts and GitHub Pages.

Moved to https://github.com/nuprl/website/issues/224.
