### ISSUE TITLE
Why are we not using a templating system?

### ISSUE THREAD

**Issue by wilbowma** [nuprl/nuprl.github.io#9]
Largish (~100 lines) chunks of code are duplicated between source files, such as the nav bar and footer. Even in files, there are patterns that could be abstracted, like seminar talk details.

Why are we not using a templating language? Particularly given the giant yellow letters on the home page: "... programming languages are therefore our fundamental tool."

**Comment by LeifAndersen** [comment]
Both Jan and I agree this would be a lot better, we're just too lazy to write one...

**Comment by wilbowma** [comment]
Write one? No no no... _use one_: http://docs.racket-lang.org/web-server/templates.html

I'm going to start converting the seminar page soonish

**Comment by wilbowma** [comment]
Will probably require some git hooks to ensure files get built before being pushed, or something.

**Comment by wilbowma** [comment]
Pushed a rewrite of the seminar page using Racket's template. It's a quick and dirty job, but serves as an example of what the rest of the site should be.

**Comment by schuster** [comment]
@wilbowma Thanks, I like it. I'll convert the rest of the pages over. I've also added a shell-script to regenerate the pages.

The next step would be to regenerate the pages automatically on check-in, but I'll make a separate issue for that.

**Comment by schuster** [comment]
Thanks for the Makefile, I didn't see that.
There's still a lot of redundant content for some individual page elements (e.g. individual people entries), but I'll let the respective page owners handle those.
